basePath: /
definitions:
  handler.CreateOrderRequest:
    properties:
      amount:
        type: integer
      description:
        type: string
      user_id:
        type: string
    type: object
  storage.Order:
    properties:
      amount:
        type: integer
      description:
        type: string
      id:
        type: string
      status:
        type: string
      user_id:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8000
info:
  contact: {}
  description: |-
    Сервис управления заказами.
    Реализует паттерн Transactional Outbox для гарантированной отправки событий в Kafka.
    Поддерживает Real-time уведомления клиентов через WebSockets.
  title: Gozon Orders API
  version: "1.0"
paths:
  /api/orders:
    get:
      description: Возвращает историю заказов пользователя
      parameters:
      - description: User UUID
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/storage.Order'
            type: array
      summary: Список заказов
      tags:
      - orders
    post:
      consumes:
      - application/json
      description: Создает заказ и асинхронно запускает процесс оплаты через Transactional
        Outbox
      parameters:
      - description: Данные заказа
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.CreateOrderRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Успешное создание
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Неверные данные
          schema:
            type: string
        "500":
          description: Внутренняя ошибка
          schema:
            type: string
      summary: Создание нового заказа
      tags:
      - orders
swagger: "2.0"
